using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Hdos.DynamicFormService.Infrastructure.Persistence.Migrations;

public partial class AddWidgetCatalog : Migration
{
    protected override void Up(MigrationBuilder migrationBuilder)
    {
        migrationBuilder.CreateTable(
            name: "WidgetCatalogs",
            columns: table => new
            {
                Id = table.Column<Guid>(type: "uuid", nullable: false),
                ChartType = table.Column<string>(type: "character varying(100)", maxLength: 100, nullable: false),
                Category = table.Column<string>(type: "character varying(50)", maxLength: 50, nullable: false),
                Label = table.Column<string>(type: "character varying(200)", maxLength: 200, nullable: false),
                Description = table.Column<string>(type: "character varying(1000)", maxLength: 1000, nullable: false),
                Icon = table.Column<string>(type: "character varying(100)", maxLength: 100, nullable: false),
                RowSchema = table.Column<string>(type: "jsonb", nullable: false),
                RequiredColumnsJson = table.Column<string>(type: "jsonb", nullable: false),
                OptionalColumnsJson = table.Column<string>(type: "jsonb", nullable: false),
                CompatibleWithJson = table.Column<string>(type: "jsonb", nullable: false),
                SortOrder = table.Column<int>(type: "integer", nullable: false)
            },
            constraints: table => table.PrimaryKey("PK_WidgetCatalogs", x => x.Id));

        migrationBuilder.CreateIndex(name: "IX_WidgetCatalogs_Category",  table: "WidgetCatalogs", column: "Category");
        migrationBuilder.CreateIndex(name: "IX_WidgetCatalogs_ChartType", table: "WidgetCatalogs", column: "ChartType", unique: true);

        var cols = new[] { "Id", "ChartType", "Category", "Label", "Description", "Icon", "RowSchema", "RequiredColumnsJson", "OptionalColumnsJson", "CompatibleWithJson", "SortOrder" };

        migrationBuilder.InsertData("WidgetCatalogs", cols, new object[] { new Guid("00000000-0000-0000-0000-000000000001"), "line_chart",         "visualization", "Biểu đồ đường",         "Xu hướng theo thời gian hoặc danh mục. Hỗ trợ nhiều series.",                        "TrendingUp",      "{}", "[\"x\",\"y\"]",                        "[\"series\",\"color\",\"annotations\"]",                                            "[\"bar_chart\",\"area_chart\"]",          10 });
        migrationBuilder.InsertData("WidgetCatalogs", cols, new object[] { new Guid("00000000-0000-0000-0000-000000000002"), "bar_chart",          "visualization", "Biểu đồ cột",           "So sánh giá trị giữa các danh mục. Hỗ trợ ngang/dọc và nhiều series.",               "BarChart2",       "{}", "[\"x\",\"y\"]",                        "[\"series\",\"color\"]",                                                            "[\"line_chart\",\"area_chart\"]",         11 });
        migrationBuilder.InsertData("WidgetCatalogs", cols, new object[] { new Guid("00000000-0000-0000-0000-000000000003"), "area_chart",         "visualization", "Biểu đồ vùng",          "Xu hướng với phần tô màu bên dưới đường. Tốt cho dữ liệu tích lũy.",                 "AreaChart",       "{}", "[\"x\",\"y\"]",                        "[\"series\",\"color\"]",                                                            "[\"line_chart\",\"bar_chart\"]",          12 });
        migrationBuilder.InsertData("WidgetCatalogs", cols, new object[] { new Guid("00000000-0000-0000-0000-000000000004"), "pie_chart",          "visualization", "Biểu đồ tròn",          "Tỷ lệ phần trăm thành phần. Tối đa 8 lát cắt khuyến nghị.",                          "PieChart",        "{}", "[\"label\",\"value\"]",               "[\"color\"]",                                                                       "[\"donut_chart\"]",                       13 });
        migrationBuilder.InsertData("WidgetCatalogs", cols, new object[] { new Guid("00000000-0000-0000-0000-000000000005"), "donut_chart",        "visualization", "Biểu đồ vòng",          "Tỷ lệ phần trăm với lỗ trống ở giữa để hiển thị tổng.",                              "Donut",           "{}", "[\"label\",\"value\"]",               "[\"color\"]",                                                                       "[\"pie_chart\"]",                         14 });
        migrationBuilder.InsertData("WidgetCatalogs", cols, new object[] { new Guid("00000000-0000-0000-0000-000000000006"), "kpi",                "visualization", "KPI đơn",               "Một chỉ số chính với so sánh và sparkline.",                                         "Hash",            "{}", "[\"value\",\"label\"]",               "[\"deltaPercent\",\"direction\",\"sparkline\",\"format\"]",                         "[\"kpi_grid\"]",                          15 });
        migrationBuilder.InsertData("WidgetCatalogs", cols, new object[] { new Guid("00000000-0000-0000-0000-000000000007"), "gauge",              "visualization", "Đồng hồ đo",            "Chỉ số dạng kim đồng hồ với ngưỡng màu sắc.",                                        "Gauge",           "{}", "[\"value\",\"min\",\"max\"]",         "[\"unit\",\"target\",\"thresholds\"]",                                              "[]",                                      16 });
        migrationBuilder.InsertData("WidgetCatalogs", cols, new object[] { new Guid("00000000-0000-0000-0000-000000000008"), "heatmap",            "visualization", "Bản đồ nhiệt",          "Dữ liệu hai chiều được tô màu theo cường độ.",                                       "Grid",            "{}", "[\"x\",\"y\",\"value\"]",            "[\"tooltip\"]",                                                                     "[]",                                      17 });
        migrationBuilder.InsertData("WidgetCatalogs", cols, new object[] { new Guid("00000000-0000-0000-0000-000000000009"), "scatter",            "visualization", "Biểu đồ phân tán",      "Phân tán điểm dữ liệu trên trục X/Y. Hỗ trợ bubble chart.",                          "ScatterChart",    "{}", "[\"x\",\"y\"]",                        "[\"size\",\"label\",\"series\",\"color\"]",                                         "[]",                                      18 });
        migrationBuilder.InsertData("WidgetCatalogs", cols, new object[] { new Guid("00000000-0000-0000-0000-000000000010"), "advanced_table",     "visualization", "Bảng nâng cao",         "Bảng phân trang phía server, sort, filter, export CSV/Excel.",                        "Table",           "{}", "[]",                                  "[]",                                                                                "[\"simple_table\"]",                      19 });
        migrationBuilder.InsertData("WidgetCatalogs", cols, new object[] { new Guid("00000000-0000-0000-0000-000000000011"), "simple_table",       "visualization", "Bảng đơn giản",         "Bảng phân trang phía client. Tối đa 1000 dòng.",                                     "List",            "{}", "[]",                                  "[]",                                                                                "[\"advanced_table\"]",                    20 });
        migrationBuilder.InsertData("WidgetCatalogs", cols, new object[] { new Guid("00000000-0000-0000-0000-000000000012"), "pivot_table",        "visualization", "Bảng pivot",            "Cross-tabulation nhiều chiều với tổng hàng/cột.",                                    "LayoutGrid",      "{}", "[]",                                  "[]",                                                                                "[]",                                      21 });
        migrationBuilder.InsertData("WidgetCatalogs", cols, new object[] { new Guid("00000000-0000-0000-0000-000000000013"), "funnel",             "visualization", "Biểu đồ phễu",          "Tỷ lệ chuyển đổi qua các bước (conversion funnel).",                                 "Filter",          "{}", "[\"label\",\"value\"]",               "[\"percentOfStart\",\"dropRate\"]",                                                 "[\"patient_flow_stages\"]",               22 });
        migrationBuilder.InsertData("WidgetCatalogs", cols, new object[] { new Guid("00000000-0000-0000-0000-000000000014"), "filter_dropdown",    "filter",        "Bộ lọc danh sách",      "Dropdown chọn một hoặc nhiều giá trị để lọc dashboard.",                             "ChevronDown",     "{}", "[\"filterKey\",\"options\"]",         "[\"currentValue\",\"multiSelect\"]",                                                "[]",                                      30 });
        migrationBuilder.InsertData("WidgetCatalogs", cols, new object[] { new Guid("00000000-0000-0000-0000-000000000015"), "filter_date_range",  "filter",        "Bộ lọc ngày",           "Chọn khoảng thời gian với preset (hôm nay, tháng này, v.v.).",                       "Calendar",        "{}", "[\"filterKey\"]",                     "[\"presets\",\"minDate\",\"maxDate\"]",                                             "[]",                                      31 });
        migrationBuilder.InsertData("WidgetCatalogs", cols, new object[] { new Guid("00000000-0000-0000-0000-000000000016"), "filter_slider",      "filter",        "Bộ lọc số",             "Thanh kéo chọn khoảng giá trị số.",                                                  "Sliders",         "{}", "[\"filterKey\",\"min\",\"max\"]",     "[\"step\",\"format\"]",                                                             "[]",                                      32 });
        migrationBuilder.InsertData("WidgetCatalogs", cols, new object[] { new Guid("00000000-0000-0000-0000-000000000017"), "filter_search",      "filter",        "Ô tìm kiếm",            "Full-text search với debounce 500ms.",                                                "Search",          "{}", "[\"filterKey\"]",                     "[\"placeholder\"]",                                                                 "[]",                                      33 });
        migrationBuilder.InsertData("WidgetCatalogs", cols, new object[] { new Guid("00000000-0000-0000-0000-000000000018"), "text_widget",        "layout",        "Văn bản / Markdown",    "Hiển thị nội dung markdown với template variable substitution.",                     "FileText",        "{}", "[\"content\"]",                       "[\"renderMode\",\"templateVariables\"]",                                            "[]",                                      40 });
        migrationBuilder.InsertData("WidgetCatalogs", cols, new object[] { new Guid("00000000-0000-0000-0000-000000000019"), "tab_container",      "layout",        "Tab container",         "Nhóm các widget theo tab. Widget trong tab không-mặc định được lazy load.",           "Tabs",            "{}", "[\"tabs\"]",                          "[]",                                                                                "[]",                                      41 });
        migrationBuilder.InsertData("WidgetCatalogs", cols, new object[] { new Guid("00000000-0000-0000-0000-000000000020"), "kpi_grid",           "healthcare",    "Lưới KPI",              "Lưới 2×5 cột các KPI card. Dùng cho overview đầu trang.",                            "LayoutDashboard", "{}", "[\"id\",\"label\",\"value\"]",        "[\"format\",\"deltaPercent\",\"direction\",\"sparkline\",\"icon\",\"variant\"]",    "[\"kpi\"]",                               50 });
        migrationBuilder.InsertData("WidgetCatalogs", cols, new object[] { new Guid("00000000-0000-0000-0000-000000000021"), "progress_rows",      "healthcare",    "Thanh tiến trình",      "Hàng thanh progress có nhãn. Dùng cho công suất giường, OR.",                        "Activity",        "{}", "[\"id\",\"label\",\"current\",\"max\"]", "[\"sublabel\",\"percent\",\"colorThresholds\",\"badge\",\"badgeVariant\"]",      "[]",                                      51 });
        migrationBuilder.InsertData("WidgetCatalogs", cols, new object[] { new Guid("00000000-0000-0000-0000-000000000022"), "flow_steps",         "healthcare",    "Luồng bước",            "Bước điều trị ngang/dọc. Dùng cho quy trình chăm sóc bệnh nhân.",                    "ArrowRight",      "{}", "[\"id\",\"label\",\"status\"]",       "[\"sublabel\",\"count\"]",                                                          "[]",                                      52 });
        migrationBuilder.InsertData("WidgetCatalogs", cols, new object[] { new Guid("00000000-0000-0000-0000-000000000023"), "timeline_vertical",  "healthcare",    "Timeline dọc",          "Dòng thời gian sự kiện theo chiều dọc. Dùng cho lịch sử bệnh nhân.",                 "Clock",           "{}", "[\"id\",\"timeLabel\",\"title\",\"status\"]", "[\"subtitle\",\"actor\",\"note\",\"isoTime\"]",                               "[]",                                      53 });
        migrationBuilder.InsertData("WidgetCatalogs", cols, new object[] { new Guid("00000000-0000-0000-0000-000000000024"), "alert_list",         "healthcare",    "Danh sách cảnh báo",    "Feed cảnh báo L1/L2/L3 real-time. Dùng cho cảnh báo lâm sàng.",                      "AlertTriangle",   "{}", "[\"id\",\"level\",\"title\",\"time\",\"acknowledged\"]", "[\"subtitle\",\"runbookId\",\"acknowledgedBy\"]",         "[]",                                      54 });
        migrationBuilder.InsertData("WidgetCatalogs", cols, new object[] { new Guid("00000000-0000-0000-0000-000000000025"), "bed_grid",           "healthcare",    "Lưới giường bệnh",      "Bản đồ giường theo khoa màu sắc. Dùng cho quản lý giường toàn viện.",                "BedDouble",       "{}", "[\"deptId\",\"deptName\",\"bedId\",\"bedLabel\",\"status\"]", "[\"floor\",\"patientId\",\"patientName\",\"admittedAt\"]", "[]",            55 });
        migrationBuilder.InsertData("WidgetCatalogs", cols, new object[] { new Guid("00000000-0000-0000-0000-000000000026"), "room_status_grid",   "healthcare",    "Trạng thái phòng",      "Lưới phòng mổ / ICU với tiến trình và thời gian. Dùng cho quản lý OR.",              "DoorOpen",        "{}", "[\"id\",\"label\",\"status\",\"primaryText\"]", "[\"secondaryText\",\"progressPercent\",\"startTime\",\"estimatedEnd\",\"badgeLabel\"]", "[]", 56 });
        migrationBuilder.InsertData("WidgetCatalogs", cols, new object[] { new Guid("00000000-0000-0000-0000-000000000027"), "map_pins",           "healthcare",    "Bản đồ ghim vị trí",    "Ghim vị trí tuyệt đối trên sơ đồ tầng / bản đồ thành phố.",                          "MapPin",          "{}", "[\"id\",\"x\",\"y\",\"label\",\"status\"]", "[\"sublabel\",\"type\",\"metadata\"]",                               "[]",                                      57 });
        migrationBuilder.InsertData("WidgetCatalogs", cols, new object[] { new Guid("00000000-0000-0000-0000-000000000028"), "patient_flow_stages","healthcare",    "Luồng bệnh nhân",       "Số bệnh nhân tại mỗi giai đoạn cấp cứu. Dùng cho ER flow.",                          "Users",           "{}", "[\"id\",\"label\",\"count\"]",        "[\"avgWaitMin\",\"status\",\"icon\"]",                                              "[\"funnel\"]",                            58 });
        migrationBuilder.InsertData("WidgetCatalogs", cols, new object[] { new Guid("00000000-0000-0000-0000-000000000029"), "risk_tiers",         "healthcare",    "Phân tầng nguy cơ",     "4 tầng nguy cơ bệnh nhân. Dùng cho quản lý sức khỏe dân số.",                        "ShieldAlert",     "{}", "[\"level\",\"label\",\"count\",\"percent\",\"color\"]", "[\"action\",\"changeFromPrev\"]",                              "[]",                                      59 });
        migrationBuilder.InsertData("WidgetCatalogs", cols, new object[] { new Guid("00000000-0000-0000-0000-000000000030"), "news2_bars",         "healthcare",    "NEWS2 Score",           "Điểm NEWS2 từng bệnh nhân với màu sắc L1/L2/L3.",                                   "HeartPulse",      "{}", "[\"id\",\"name\",\"score\",\"level\"]", "[\"ward\",\"bed\",\"trend\",\"components\",\"lastAssessed\",\"alertSent\"]",  "[]",                                      60 });
        migrationBuilder.InsertData("WidgetCatalogs", cols, new object[] { new Guid("00000000-0000-0000-0000-000000000031"), "chat_panel",         "ai",            "AI Chatbot",            "Trợ lý AI nhúng vào dashboard. Kết nối với operation AI.",                           "MessageSquare",   "{}", "[]",                                  "[\"systemRole\",\"operationPattern\",\"quickQuestions\",\"allowedRoles\"]",         "[]",                                      70 });
    }

    protected override void Down(MigrationBuilder migrationBuilder)
    {
        migrationBuilder.DropTable(name: "WidgetCatalogs");
    }
}
