<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>Hdos.OrderService.Application</RootNamespace>
    <AssemblyName>Hdos.OrderService.Application</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="FluentValidation" Version="11.10.0" />
    <PackageReference Include="FluentValidation.DependencyInjectionExtensions" Version="11.10.0" />
    <PackageReference Include="MediatR" Version="12.4.1" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="8.0.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\OrderService.Domain\OrderService.Domain.csproj" />
    <ProjectReference Include="..\..\..\BuildingBlocks\Common\Common.csproj" />
    <ProjectReference Include="..\..\..\BuildingBlocks\Contracts\Contracts.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Features\Products\" />
  </ItemGroup>

</Project>
