<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>Hdos.M01Service.API</RootNamespace>
    <AssemblyName>Hdos.M01Service.API</AssemblyName>
    <UserSecretsId>hdos-m01-service</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="8.0.10">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.8.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\M01Service.Application\M01Service.Application.csproj" />
    <ProjectReference Include="..\M01Service.Infrastructure\M01Service.Infrastructure.csproj" />
    <ProjectReference Include="..\..\..\BuildingBlocks\Common\Common.csproj" />
  </ItemGroup>

</Project>
