using FluentAssertions;
using Hdos.Contracts.IntegrationEvents;
using Xunit;

namespace Hdos.BuildingBlocks.Tests.Contracts;

public sealed class IntegrationEventTests
{
    private sealed record SampleEvent(string Payload) : IntegrationEvent;

    [Fact]
    public void NewEvent_GetsAutoGeneratedId()
    {
        var a = new SampleEvent("x");
        var b = new SampleEvent("x");

        a.EventId.Should().NotBeEmpty();
        b.EventId.Should().NotBeEmpty();
        a.EventId.Should().NotBe(b.EventId);
    }

    [Fact]
    public void NewEvent_GetsRecentTimestamp()
    {
        var before = DateTime.UtcNow;
        var e = new SampleEvent("x");
        var after = DateTime.UtcNow;

        e.OccurredOnUtc.Should().BeOnOrAfter(before).And.BeOnOrBefore(after);
    }

    [Fact]
    public void EventType_ReflectsRuntimeType()
    {
        IntegrationEvent e = new SampleEvent("x");

        e.EventType.Should().Be(nameof(SampleEvent));
    }
}
